const totalCoursesExample = 5;

const skipCoursesExample = 0;

const limitCoursesExample = 30;

const newCourseDtoExample = #{
  title: "New course",
  description: "description"
};

const editCourseDtoExample = #{
  title: "Edited course",
  description: "new description",
};

const courseExample = #{
  id: "cb9b5981-c34d-49a5-8a44-1b1b96788123",
  title: "Курс PHP",
  description: "Курс знакомит с основами языка программирования PHP"
};

const coursesExample = #[
  courseExample,
  #{
    id: "13e3ecf2-c37e-461a-bdd4-bb069329c914",
    title: "Курс Ruby",
    description: "Курс знакомит с основами языка программирования Ruby"
  },
  #{
    id: "a0d29a74-13c7-4ca9-b6ce-e2a59508ac82",
    title: "Курс JavaScript",
    description: "Курс знакомит с основами языка программирования JavaScript"
  },
  #{
    id: "afaf1d20-701d-494a-9589-7d3bc780b300",
    title: "Курс Python",
    description: "Курс знакомит с основами языка программирования Python"
  },
  #{
    id: "6e32e36d-40d1-4bc4-bdcb-966f01748b17",
    title: "Курс Java",
    description: "Курс знакомит с основами языка программирования Java"
  }
];
