const totalUsersExample = 5;

const skipUsersExample = 0;

const limitUsersExample = 30;

const newUserDtoExample = #{
  email: "max@yahoo.com",
  firstName: "Max",
  lastName: "Maxwell",
  password: "password"
};

const editUserDtoExample = #{
  email: "maria@yahoo.com",
  firstName: "Maria",
  lastName: "Marvel"
};

const userExample = #{
  id: "1",
  email: "max@hotmail.com",
  firstName: "Allison",
  lastName: "Bernier",
};

const usersExample = #[
  userExample,
  #{
    id: "2",
    email: "Colt97@yahoo.com",
    firstName: "Hudson",
    lastName: "Schowalter"
  },
  #{
    id: "3",
    email: "Landen50@gmail.com",
    firstName: "Reinhold",
    lastName: "Upton"
  },
  #{
    id: "4",
    email: "Americo_Jones@hotmail.com",
    firstName: "Fabian",
    lastName: "Larson-Cassin"
  },
  #{
    id: "5",
    email: "Glenna.Kshlerin81@yahoo.com",
    firstName: "Verlie",
    lastName: "Bauch"
  },
  #{
    id: "6",
    email: "Jamie.Volkman@gmail.com",
    firstName: "Marcelle",
    lastName: "Collier"
  },
  #{
    id: "7",
    email: "Meghan.Emmerich49@gmail.com",
    firstName: "Easton",
    lastName: "Halvorson"
  },
  #{
    id: "8",
    email: "Ophelia_Nikolaus73@gmail.com",
    firstName: "Althea",
    lastName: "Leannon"
  },
  #{
    id: "9",
    email: "Jovanny.Tromp3@gmail.com",
    firstName: "Savion",
    lastName: "King"
  },
  #{
    id: "10",
    email: "Aniyah_Macejkovic@gmail.com",
    firstName: "Magali",
    lastName: "Carroll"
  }
];
